on:
  workflow_call:

jobs:
  testVerdaccio:
    name: Test Verdaccio Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Publish
      uses: verdaccio/github-actions/publish@2f06fdf8e5f363a151d6dd8194032381ea8b6594 # tag=v0.4.0
      with:
        args: -d
